import { prisma } from '@/lib/prisma';
import * as v from '@/lib/schemas/resources';
import * as s from '@/lib/schemas/selling';

import type { ResourceConfig, ResourceDelegate } from './resource';

/**
 * Prisma generates a distinct delegate type per model; the handlers only use
 * the common subset described by `ResourceDelegate`.
 */
const delegate = (model: unknown) => model as unknown as ResourceDelegate;

export const resources = {
  entities: {
    delegate: delegate(prisma.entity),
    label: 'Entity',
    createSchema: v.entityCreateSchema,
    updateSchema: v.entityUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
  },
  persons: {
    delegate: delegate(prisma.person),
    label: 'Person',
    createSchema: v.personCreateSchema,
    updateSchema: v.personUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
  },
  'entity-persons': {
    delegate: delegate(prisma.entityPerson),
    label: 'EntityPerson',
    createSchema: v.entityPersonCreateSchema,
    updateSchema: v.entityPersonUpdateSchema,
    orderBy: 'created_at',
    archivable: false,
    filters: ['entity_id', 'person_id'],
    dateOnlyFields: ['started_on', 'ended_on'],
  },
  deals: {
    delegate: delegate(prisma.deal),
    label: 'Deal',
    createSchema: v.dealCreateSchema,
    updateSchema: v.dealUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
    dateOnlyFields: ['expected_close_date'],
  },
  cases: {
    delegate: delegate(prisma.supportCase),
    label: 'Case',
    createSchema: v.caseCreateSchema,
    updateSchema: v.caseUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
  },
  incidents: {
    delegate: delegate(prisma.incident),
    label: 'Incident',
    createSchema: v.incidentCreateSchema,
    updateSchema: v.incidentUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
  },
  'incident-cases': {
    delegate: delegate(prisma.incidentCase),
    label: 'IncidentCase',
    createSchema: v.incidentCaseCreateSchema,
    updateSchema: v.incidentCaseUpdateSchema,
    orderBy: 'linked_at',
    archivable: false,
    filters: ['incident_id', 'case_id'],
  },
  requests: {
    delegate: delegate(prisma.featureRequest),
    label: 'Request',
    createSchema: v.requestCreateSchema,
    updateSchema: v.requestUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
    dateOnlyFields: ['target_date'],
  },
  'chat-channels': {
    delegate: delegate(prisma.chatChannel),
    label: 'Chat channel',
    createSchema: v.chatChannelCreateSchema,
    updateSchema: v.chatChannelUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
  },
  'chat-contacts': {
    delegate: delegate(prisma.chatContact),
    label: 'Chat contact',
    createSchema: v.chatContactCreateSchema,
    updateSchema: v.chatContactUpdateSchema,
    orderBy: 'created_at',
    archivable: false,
    filters: ['channel_id', 'person_id', 'entity_id'],
  },
  'chat-conversations': {
    delegate: delegate(prisma.chatConversation),
    label: 'Chat conversation',
    createSchema: v.chatConversationCreateSchema,
    updateSchema: v.chatConversationUpdateSchema,
    // The inbox is ordered by activity, not by when a thread was opened.
    orderBy: 'last_message_at',
    archivable: false,
    filters: ['channel_id', 'contact_id', 'entity_id', 'person_id', 'deal_id', 'case_id'],
  },
  'chat-messages': {
    delegate: delegate(prisma.chatMessage),
    label: 'Chat message',
    createSchema: v.chatMessageCreateSchema,
    updateSchema: v.chatMessageUpdateSchema,
    orderBy: 'created_at',
    archivable: false,
    filters: ['conversation_id'],
  },

  /* Selling — catalog ------------------------------------------------------ */
  products: {
    delegate: delegate(prisma.product),
    label: 'Product',
    createSchema: s.productCreateSchema,
    updateSchema: s.productUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
  },
  offerings: {
    delegate: delegate(prisma.offering),
    label: 'Offering',
    createSchema: s.offeringCreateSchema,
    updateSchema: s.offeringUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
    filters: ['product_id'],
    dateOnlyFields: ['active_from', 'active_until'],
  },
  'price-books': {
    delegate: delegate(prisma.priceBook),
    label: 'Price book',
    createSchema: s.priceBookCreateSchema,
    updateSchema: s.priceBookUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
    filters: ['entity_id'],
    dateOnlyFields: ['active_from', 'active_until'],
  },
  prices: {
    delegate: delegate(prisma.price),
    label: 'Price',
    createSchema: s.priceCreateSchema,
    updateSchema: s.priceUpdateSchema,
    orderBy: 'created_at',
    archivable: false,
    filters: ['offering_id', 'price_book_id'],
    dateOnlyFields: ['effective_from', 'effective_until'],
  },
  'price-tiers': {
    delegate: delegate(prisma.priceTier),
    label: 'Price tier',
    createSchema: s.priceTierCreateSchema,
    updateSchema: s.priceTierUpdateSchema,
    // Bands read low to high, the way they are charged.
    orderBy: 'up_to',
    orderDirection: 'asc',
    archivable: false,
    filters: ['price_id'],
  },
  'bundle-components': {
    delegate: delegate(prisma.bundleComponent),
    label: 'Bundle component',
    createSchema: s.bundleComponentCreateSchema,
    updateSchema: s.bundleComponentUpdateSchema,
    orderBy: 'sort_order',
    orderDirection: 'asc',
    archivable: false,
    filters: ['parent_offering_id', 'child_offering_id'],
  },
  'inventory-items': {
    delegate: delegate(prisma.inventoryItem),
    label: 'Inventory item',
    createSchema: s.inventoryItemCreateSchema,
    updateSchema: s.inventoryItemUpdateSchema,
    orderBy: 'created_at',
    archivable: false,
    filters: ['offering_id'],
  },
  'service-definitions': {
    delegate: delegate(prisma.serviceDefinition),
    label: 'Service definition',
    createSchema: s.serviceDefinitionCreateSchema,
    updateSchema: s.serviceDefinitionUpdateSchema,
    orderBy: 'created_at',
    archivable: false,
    filters: ['offering_id'],
  },

  /* Selling — transactions -------------------------------------------------- */
  'deal-lines': {
    delegate: delegate(prisma.dealLine),
    label: 'Deal line',
    createSchema: s.dealLineCreateSchema,
    updateSchema: s.dealLineUpdateSchema,
    orderBy: 'sort_order',
    orderDirection: 'asc',
    archivable: false,
    filters: ['deal_id', 'offering_id'],
  },
  quotes: {
    delegate: delegate(prisma.quote),
    label: 'Quote',
    createSchema: s.quoteCreateSchema,
    updateSchema: s.quoteUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
    filters: ['entity_id', 'deal_id'],
    dateOnlyFields: ['valid_from', 'valid_until'],
  },
  'quote-lines': {
    delegate: delegate(prisma.quoteLine),
    label: 'Quote line',
    createSchema: s.quoteLineCreateSchema,
    updateSchema: s.quoteLineUpdateSchema,
    orderBy: 'sort_order',
    orderDirection: 'asc',
    archivable: false,
    filters: ['quote_id', 'parent_quote_line_id'],
  },
  orders: {
    delegate: delegate(prisma.order),
    label: 'Order',
    createSchema: s.orderCreateSchema,
    updateSchema: s.orderUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
    filters: ['entity_id', 'quote_id', 'deal_id'],
  },
  'order-lines': {
    delegate: delegate(prisma.orderLine),
    label: 'Order line',
    createSchema: s.orderLineCreateSchema,
    updateSchema: s.orderLineUpdateSchema,
    orderBy: 'sort_order',
    orderDirection: 'asc',
    archivable: false,
    filters: ['order_id', 'quote_line_id', 'offering_id'],
  },

  /* Selling — fulfillment and delivery -------------------------------------- */
  shipments: {
    delegate: delegate(prisma.shipment),
    label: 'Shipment',
    createSchema: s.shipmentCreateSchema,
    updateSchema: s.shipmentUpdateSchema,
    orderBy: 'created_at',
    archivable: false,
    filters: ['order_id'],
  },
  'shipment-lines': {
    delegate: delegate(prisma.shipmentLine),
    label: 'Shipment line',
    createSchema: s.shipmentLineCreateSchema,
    updateSchema: s.shipmentLineUpdateSchema,
    orderBy: 'created_at',
    orderDirection: 'asc',
    archivable: false,
    filters: ['shipment_id', 'order_line_id'],
  },
  subscriptions: {
    delegate: delegate(prisma.subscription),
    label: 'Subscription',
    createSchema: s.subscriptionCreateSchema,
    updateSchema: s.subscriptionUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
    filters: ['entity_id', 'order_id', 'order_line_id'],
    dateOnlyFields: [
      'start_date',
      'end_date',
      'current_period_start',
      'current_period_end',
      'commitment_end_date',
      'trial_end_date',
      'resumes_on',
      'cancellation_effective_date',
    ],
  },
  'subscription-amendments': {
    delegate: delegate(prisma.subscriptionAmendment),
    label: 'Subscription amendment',
    createSchema: s.subscriptionAmendmentCreateSchema,
    updateSchema: s.subscriptionAmendmentUpdateSchema,
    orderBy: 'created_at',
    archivable: false,
    filters: ['subscription_id'],
    dateOnlyFields: ['effective_date', 'previous_commitment_end_date', 'new_commitment_end_date'],
  },
  entitlements: {
    delegate: delegate(prisma.entitlement),
    label: 'Entitlement',
    createSchema: s.entitlementCreateSchema,
    updateSchema: s.entitlementUpdateSchema,
    orderBy: 'created_at',
    orderDirection: 'asc',
    archivable: false,
    filters: ['subscription_id', 'entity_id', 'order_line_id'],
    dateOnlyFields: ['effective_from', 'effective_until'],
  },
  'usage-records': {
    delegate: delegate(prisma.usageRecord),
    label: 'Usage record',
    createSchema: s.usageRecordCreateSchema,
    updateSchema: s.usageRecordUpdateSchema,
    orderBy: 'occurred_at',
    archivable: false,
    filters: ['subscription_id', 'entitlement_id', 'entity_id', 'order_line_id'],
  },
  'service-deliveries': {
    delegate: delegate(prisma.serviceDelivery),
    label: 'Service delivery',
    createSchema: s.serviceDeliveryCreateSchema,
    updateSchema: s.serviceDeliveryUpdateSchema,
    orderBy: 'created_at',
    archivable: true,
    filters: ['entity_id', 'order_id', 'order_line_id', 'case_id', 'incident_id'],
  },
  'service-milestones': {
    delegate: delegate(prisma.serviceMilestone),
    label: 'Service milestone',
    createSchema: s.serviceMilestoneCreateSchema,
    updateSchema: s.serviceMilestoneUpdateSchema,
    orderBy: 'sequence',
    orderDirection: 'asc',
    archivable: false,
    filters: ['service_delivery_id'],
    dateOnlyFields: ['due_on'],
  },
  notes: {
    delegate: delegate(prisma.note),
    label: 'Note',
    createSchema: v.noteCreateSchema,
    updateSchema: v.noteUpdateSchema,
    orderBy: 'created_at',
    archivable: false,
    filters: ['parent_id'],
  },
} as const satisfies Record<string, ResourceConfig>;

export type ResourceName = keyof typeof resources;
